spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/itb_attendance_management?characterEncoding=utf8
    username: root
    password: mysql
    driverClassName: com.mysql.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE